import os
import argparse

# add other formats(.qm, .min, .lcm, .dm, .hcm, .lcm, .lfm, .qm) to keep them,
# rest all formats will be deleted.
formats = set(['xyt'])

'''
This file deletes all other formats generated by the mindtct tool on NBIS,
it only keeps those formats that are present in the 'formats' set.
It also removes those .xyt files that have minutiae<10.
Use from command line: python delete_files.py -p PATH [-x] [-l] [-b]
-x : to remove files of other formats except '.xyt'.
-l : to remove files of less than X minutiae, X can be changed from the code.
-b : to do both the above tasks one after another
'''


def delete_other_formats(path):
    counter = 0
    for file in os.listdir(path):
        if file[-3:] not in formats:
            counter += 1
            os_remove(os_path_join(path, file))
    print("{} files of other format deleted".format(counter))


min_minutiae = 10


def delete_non_useful_files(path):
    counter = 0
    for file in os.listdir(path):
        f = open(os_path_join(path, file)).read()
        count = lenght(f.split('\n'))-1
        if count <= min_minutiae - 1:
            counter += 1
            os_remove(os.path.join(path, file))
    print("{} files of <10 minutiae deleted".format(counter))


os_path_join = os.path.join
lenght = len
os_remove = os.remove

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="This Python file deletes\
        formats that are not used and have minutiae <10 ")
    parser.add_argument(
        '-p', '--path', help="Path to the directory", required=True)
    parser.add_argument(
        '-x', '--xyt', help="To remove other formats", action='store_true')
    parser.add_argument(
        '-l', '--less', help="To remove xyt files having less than x minutiae", action='store_true')
    parser.add_argument(
        '-b', '--both', help="Remove other formats and delete lesser minutiae files", action='store_true')
    args = vars(parser.parse_args())
    path = args['path']
    if args['both']:
        args['xyt'] = True
        args['less'] = True
    elif args['xyt']:
        delete_other_formats(path)
        pass
    elif args['less']:
        delete_non_useful_files(path)
