import os
import argparse

# add other formats(.qm, .min, .lcm, .dm, .hcm, .lcm, .lfm, .qm) to keep them,
# rest all formats will be deleted.
formats = set(['xyt'])

'''
This file deletes all other formats generated by the mindtct tool on NBIS,
it only keeps those formats that are present in the format set.
It also removes those .xyt files that have minutiae<10.
Use from command line: python delete_files.py -p [path]
'''


def delete_other_formats(path):
    counter = 0
    for file in os.listdir(path):
        if file[-3:] not in formats:
            counter += 1
            os.remove(os.path.join(path, file))
    print("{} files of other format deleted".format(counter))


def delete_non_useful_files(path):
    counter = 0
    for file in os.listdir(path):
        f = open(os.path.join(path, file)).read()
        count = len(f.split('\n'))-1
        if count <= 9:
            counter += 1
            os.remove(os.path.join(path, file))
    print("{} files of <10 minutiae deleted".format(counter))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="This Python file deletes\
        formats that are not used and have minutiae <10 ")
    parser.add_argument(
        '-p', '--path', help="Path to the directory", required=True)
    args = vars(parser.parse_args())
    path = args['path']

    delete_other_formats(path)
    delete_non_useful_files(path)
