import os
import argparse

'''
This Python generates the .xyt files from the given .jpeg or .wsq image,
in addition to the .xyt files, the mindtct, program of NBIS also generates
other formats, which can be removed using a seperate Pyhton file named
'delete_files.py'. Provide the path of the directory containing the images
and path of the directory to store the files generated by the mindtct program.
Make sure that mindtct in available on your path for this code to work
correctly, if your don't want to add mindtct to yout path, change it here.
'''
# Change this according to path in your system,
# Do not change if mindtctc is added to the path
mindtct_path = "mindtct"

os_path_join = os.path.join


def run_mindtct(source_path, save_path):
    for image in os.listdir(source_path):
        image_name = image.split('.')[0]
        os.system(
            " ".join([mindtct_path, os_path_join(source_path, image), os_path_join(save_path, image_name)]))


if __name__ == "__main__":
    # code for cli arguments
    parser = argparse.ArgumentParser(description='desc')
    parser.add_argument(
        '-p', '--path', help='Required. Path to the source directory', required=True)
    parser.add_argument(
        '-s', '--save', help='Required. Path to the destination directory', required=True)
    args = vars(parser.parse_args())
    run_mindtct(args['path'], args['save'])
